[workspace.package]
version = "1.0.0"
edition = "2021"

[workspace]
members = [
    "bin/deamon",
    "bin/client",
    "redis_client",
    "price_client",
]

default-members = [
    "bin/deamon",
    "bin/client",
]

[workspace.dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96" } 
tokio = { version = "1", features = ["full"] }
redis = { version = "0.23.0", features = ["tokio-comp", "json"] }