version: '3.8'
services:
  app_build:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
  client:
    image: app
    environment:
        ROCKET_ADDRESS: 0.0.0.0
        BINARY: client
        REDIS_URL: "redis://default:@localhost:6379"
    ports:
      - "8000:8000"
      - "443:8000"
    depends_on:
      - app_build
      - redis
  deamon:
    image: app
    environment:
      BINARY: deamon
      REDIS_URL: "redis://default:@localhost:6379"
    depends_on:
      - app_build
      - redis
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    network_mode: "host"
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local