[redis]
url = "redis://default:@localhost:6379"

[coingecko.key]
secret = ""

[fiat]
timeout = 3

[moonpay]
[moonpay.key]
public = ""
secret = ""

[transak]
[transak.key]
public = ""

[mercuryo]
[mercuryo.key]
public = ""

[ramp]
[ramp.key]
public = ""

[pricer]
timer = 180

[plausible]
url = "https://plausible.gemwallet.com"